# Generated by Django 4.2.7 on 2026-03-10 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternate Phone')),
                ('business_name', models.CharField(max_length=200, verbose_name='Business/Company Name')),
                ('business_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('private_limited', 'Private Limited'), ('public_limited', 'Public Limited'), ('llp', 'LLP (Limited Liability Partnership)'), ('non_profit', 'Non-Profit Organization'), ('government', 'Government'), ('individual', 'Individual'), ('other', 'Other')], default='individual', max_length=50, verbose_name='Business Type')),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='GST Number')),
                ('pan_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='PAN Number')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('pincode', models.CharField(max_length=20, verbose_name='Pincode')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id'], name='customers_c_custome_ec5e63_idx'), models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['business_name'], name='customers_c_busines_cf5dc7_idx'), models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx')],
            },
        ),
    ]
