# Generated by Django 4.2.7 on 2026-03-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_company_remove_user_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_password',
            field=models.CharField(blank=True, help_text='Password for customer email authentication', max_length=128, null=True),
        ),
    ]
