# Generated by Django 4.2.7 on 2026-03-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_tickets_tic_assigne_e36302_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
